#ARG REGISTRY_NAME
#FROM doclancontainerstaging.azurecr.io/baseimages/node:15-alpine
FROM doclancontainerstaging.azurecr.io/phuongbaseimage

#FROM ${REGISTRY_NAME}/baseimages/node:15-alpine


COPY . /src
RUN cd /src && npm install
EXPOSE 80
CMD ["node", "/src/server.js"]
